name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  deploy:
    name: deploy to EC2
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout files
        uses: actions/checkout@v4

      - name: Install SSH client
        run: sudo apt-get install openssh-client -y

      - name: Copy dist folder to EC2
        uses: easingthemes/ssh-deploy@main
        with:
          REMOTE_HOST: 'ec2-18-205-234-10.compute-1.amazonaws.com'
          REMOTE_USER: 'ubuntu'
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          SOURCE: 'dist/*'
          target: '/var/www/html/'
